image: osakared/haxe-ci

test:
  script:
   - lix download
   - git submodule init
   - git submodule update
   - haxelib git grig.plugin https://gitlab.com/haxe-grig/grig.plugin.git
   - haxelib dev grig.plugin `pwd`
   - haxe tests.hxml -cpp bin/cpp                   && ./bin/cpp/RunTests

trigger_build:
  stage: deploy
  script:
    - "curl -X POST -F \"token=$CI_JOB_TOKEN\" -F ref=master https://gitlab.com/api/v4/projects/6741415/trigger/pipeline"