sudo: required
dist: trusty

language: node_js
node_js: 6

os:
  - linux
  - osx
  - windows

install:
  - npm install -g lix

script:
  - lix download
  - git submodule init
  - git submodule update
  - haxelib git grig.plugin https://gitlab.com/haxe-grig/grig.plugin.git
  - haxelib dev grig.plugin `pwd`
  - haxe tests.hxml && ./bin/tests/RunTests
